{
 "title": "Internet Stats",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Download",
   "type": "gauge",
   "description": "Download Speed",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "downloadSpeed{job=\"internet-stats\"}"
    }
   ]
  },
  {
   "title": "Speed history ",
   "type": "timeseries",
   "description": "Speed over time",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 0 },
   "targets": [
    { "expr": "downloadSpeed" }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "description": "Internet latency",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "latency" }
   ]
  },
  {
   "title": "Latency History",
   "type": "histogram",
   "description": "Latency overtime ",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 7 },
   "targets": [
    { "expr": "latency" }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "description": "Average upload speed",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(uploadSpeed)" }
   ]
  },
  {
   "title": "Tests conducted",
   "type": "stat",
   "description": "No of times this test has been run ",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tests_conducted" }
   ]
  }
 ]
}